# Generated by Django 5.1.3 on 2024-11-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('required_fields', models.JSONField(default=list)),
                ('lt_regulations', models.URLField(blank=True, null=True)),
                ('en_regulations', models.URLField(blank=True, null=True)),
                ('registration_deadline', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
                ('gender_male', models.BooleanField(default=False)),
                ('gender_female', models.BooleanField(default=False)),
                ('sorting_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RaceDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lt', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('additional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='api.event')),
                ('groups', models.ManyToManyField(blank=True, to='api.group')),
            ],
        ),
    ]
