# Generated by Django 5.1.3 on 2024-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_lt', models.CharField(db_column='Name_LT')),
                ('name_en', models.CharField(db_column='Name_EN')),
                ('numbers', models.CharField(db_column='Numbers')),
                ('special_numbers', models.CharField(db_column='Special_numbers')),
                ('price', models.CharField(db_column='Price')),
                ('price_extra', models.CharField(db_column='Price_extra')),
                ('price_extra_date', models.DateField(db_column='Price_extra_date')),
                ('if_race', models.BooleanField(db_column='If_race')),
                ('race_participant_count', models.IntegerField(db_column='Race_participant_count')),
            ],
            options={
                'db_table': 'Distance',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name')),
                ('required_participant_fields', models.CharField(db_column='Required_participant_fields')),
                ('reglament_lt', models.CharField(db_column='Reglament_LT')),
                ('reglament_en', models.CharField(db_column='Reglament_EN')),
            ],
            options={
                'db_table': 'sports_event',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('age', models.CharField(db_column='Age', max_length=255)),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
    ]
